### PR TITLE
redirect instead of overwrite

### PR DESCRIPTION
**Pull request by contariaa**

### CODE REVIEW

**Comment by HowardZHY** [comment]
will that work ingame?

**Comment by HowardZHY** [comment]
I think I'd better test it on my computer before merge

**Comment by contariaa** [comment]
it should work exactly the same, i saw you used intermediary before tho is there a reason for that?

**Comment by contariaa** [comment]
> I think I'd better test it on my computer before merge

yea of course, do that

**Comment by HowardZHY** [comment]
damn, I have to edit gradle.properties back to 1.8.9 on my computer

**Comment by HowardZHY** [comment]
```@Redirect(method = {"handleKeyboard"}``` wasn't remaped to Intermediary after build see
[LegacyInputPatch.zip](https://github.com/HowardZHY/LegacyInputPatch/files/9814316/LegacyInputPatch.zip)

**Comment by contariaa** [comment]
okay i changed it

**Comment by HowardZHY** [comment]
1.8 tested

**Comment by HowardZHY** [comment]
1.7.10 tested. could u bump version to 1.0.2?

**Comment by NoobKiller1919** [comment]
The stupid @Overwrite makes the pretentious you look like a clown🤣

**Pull request merged**
